### ISSUE TITLE
`/etc/init.d/openibd restart` consistently failing in Azure NDm_A100_v4

### ISSUE THREAD

**Issue by chewong** [Mellanox/doca-driver-build#52]
We have a Kubernetes cluster on Azure with worker nodes using the [NDm_A100_v4](https://learn.microsoft.com/en-us/azure/virtual-machines/sizes/gpu-accelerated/ndma100v4-series?tabs=sizebasic) VM size, which is supposed to have 8 CX-6 NICs. We installed the latest network-operator with the latest DOCA driver, but it consistently fails at this step: https://github.com/Mellanox/doca-driver-build/blob/main/entrypoint.sh#L511.

The driver builds successfully, but when running `/etc/init.d/openibd restart`:

```
+ exec_cmd '/etc/init.d/openibd restart'
+ debug_print 'Executing command: /etc/init.d/openibd restart'
+ true
+ timestamp_print 'Executing command: /etc/init.d/openibd restart'
++ date +%d-%b-%y_%H:%M:%S
+ date_time_stamp=21-Mar-25_03:03:09
+ msg='[21-Mar-25_03:03:09] Executing command: /etc/init.d/openibd restart'
+ echo '[21-Mar-25_03:03:09] Executing command: /etc/init.d/openibd restart'
+ tee -a /tmp/entrypoint_debug_cmds.log
[21-Mar-25_03:03:09] Executing command: /etc/init.d/openibd restart
++ eval '/etc/init.d/openibd restart'
+++ /etc/init.d/openibd restart
+ output='Unloading HCA driver:[  OK  []
Failed loading kernel module mlx5_ib:[FAILED[]
Loading Mellanox MLX5_IB HCA driver:[FAILED[]
Loading HCA driver and Access Layer:[FAILED[]
mofed-container
Unloading HCA driver:[  OK  []
Failed loading kernel module mlx5_ib:[FAILED[]
Loading Mellanox MLX5_IB HCA driver:[FAILED[]
Loading HCA driver and Access Layer:[FAILED[]
mofed-container
Please open an issue in the http://support.mellanox.com/SupportWeb/service_center/SelfService and attach /tmp/ib_debug_info.log
Please open an issue in the http://support.mellanox.com/SupportWeb/service_center/SelfService and attach /tmp/ib_debug_info.log'
+ exit_code=1
+ echo 'Unloading HCA driver:[  OK  []
Failed loading kernel module mlx5_ib:[FAILED[]
Loading Mellanox MLX5_IB HCA driver:[FAILED[]
Loading HCA driver and Access Layer:[FAILED[]'
```

Inspecting `dmesg`, it’s filled with this error:

```
...
[ 2198.579554] mlx5_ib: disagrees about version of symbol mlx5_eswitch_add_send_to_vport_rule
[ 2198.579559] mlx5_ib: Unknown symbol mlx5_eswitch_add_send_to_vport_rule (err -22)
...
```

FWIW we also tried a different VM size, NDasrA100_v4, which also has 8 Mellanox NICs, and the DOCA driver installed successfully there. I’d appreciate any insights you have.

Log file:

[ib_debug_info.log](https://github.com/user-attachments/files/19380356/ib_debug_info.log)

**Comment by rollandf** [comment]
Hey, can you supply the exact DOCA-Driver container version/tag?
Also, please attach the full log of the container.
Thanks

**Comment by surajssd** [comment]
@rollandf I recreated the above problem. The `nicclusterpolicy` used is this and specifically the `25.01-0.6.0.0-0` driver version:

```yaml
apiVersion: mellanox.com/v1alpha1
kind: NicClusterPolicy
metadata:
  name: nic-cluster-policy
spec:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: feature.node.kubernetes.io/pci-15b3.present
          operator: In
          values:
          - "true"
  ofedDriver:
    forcePrecompiled: false
    image: doca-driver
    imagePullSecrets: []
    livenessProbe:
      initialDelaySeconds: 30
      periodSeconds: 30
    readinessProbe:
      initialDelaySeconds: 10
      periodSeconds: 30
    repository: nvcr.io/nvidia/mellanox
    startupProbe:
      initialDelaySeconds: 10
      periodSeconds: 20
    terminationGracePeriodSeconds: 300
    upgradePolicy:
      autoUpgrade: true
      drain:
        deleteEmptyDir: true
        enable: true
        force: true
        timeoutSeconds: 300
      maxParallelUpgrades: 1
      safeLoad: false
    version: 25.01-0.6.0.0-0
```

The helm chart version:

```console
✗ helm ls -n network-operator
NAME                    NAMESPACE               REVISION        UPDATED                                 STATUS          CHART                   APP VERSION
network-operator        network-operator        1               2025-03-26 12:53:44.403435 -0700 PDT    deployed        network-operator-25.1.0 v25.1.0
```

Other logs & configs files:

- Driver pod [mofed-ubuntu22.04-54cb554cbd-ds-9rvxf](https://gist.github.com/surajssd/f51a20f22deb85ec55d6a7e42c44a996#file-mofed-ubuntu22-04-54cb554cbd-ds-9rvxf)
- Driver pod verbose: [mofed-ubuntu22.04-54cb554cbd-ds-9rvxf-verbose](https://gist.github.com/surajssd/f51a20f22deb85ec55d6a7e42c44a996#file-mofed-ubuntu22-04-54cb554cbd-ds-9rvxf-verbose)
- [entrypoint_debug_cmds.log](https://gist.github.com/surajssd/f51a20f22deb85ec55d6a7e42c44a996#file-entrypoint_debug_cmds-log)
- [ib_debug_info.log](https://gist.github.com/surajssd/f51a20f22deb85ec55d6a7e42c44a996#file-ib_debug_info-log)
- Driver Daemonset config [mofed-ubuntu22.04-54cb554cbd-ds.yaml](https://gist.github.com/surajssd/f51a20f22deb85ec55d6a7e42c44a996#file-mofed-ubuntu22-04-54cb554cbd-ds-yaml)
